export const PRODUCT_GET_REQUEST = 'PRODUCT_GET_REQUEST'
export const PRODUCT_GET_SUCCESS = 'PRODUCT_GET_SUCCESS'
export const PRODUCT_GET_FAIL = 'PRODUCT_GET_FAIL'

export const PRODUCT_GET_DISCOUNT_REQUEST = 'PRODUCT_GET_DISCOUNT_REQUEST'
export const PRODUCT_GET_DISCOUNT_SUCCESS = 'PRODUCT_GET_DISCOUNT_SUCCESS'
export const PRODUCT_GET_DISCOUNT_FAIL = 'PRODUCT_GET_DISCOUNT_FAIL'

export const PRODUCT_SAMSUNG_GET_DISCOUNT_REQUEST =
  'PRODUCT_SAMSUNG_GET_DISCOUNT_REQUEST'
export const PRODUCT_SAMSUNG_GET_DISCOUNT_SUCCESS =
  'PRODUCT_SAMSUNG_GET_DISCOUNT_SUCCESS'
export const PRODUCT_SAMSUNG_GET_DISCOUNT_FAIL =
  'PRODUCT_SAMSUNG_GET_DISCOUNT_FAIL'

export const PRODUCT_GET_BY_ID_REQUEST = 'PRODUCT_GET_BY_ID_REQUEST'
export const PRODUCT_GET_BY_ID_SUCCESS = 'PRODUCT_GET_BY_ID_SUCCESS'
export const PRODUCT_GET_BY_ID_FAIL = 'PRODUCT_GET_BY_ID_FAIL'
