export default {
  EMAIL_EXIST: 'This email address is already exists, try with a different email address',
  PHONE_EXIST: 'This phone number is already exists, try with a different phone number',
  WRONG_EMAIL_FORMAT: 'Invalid email address',
  SIGNUP_MAILING_SUBJECT: 'Xin chào! Yêu cầu kích hoạt tài khoản',
  SIGNUP_MAILING_HTML:
    '<p>Xin chào %s. Hệ thống đã gửi yêu cầu kích hoạt tài khoản, vui lòng nhấn vào link sau để kích hoạt tài khoản của bạn. Link sẽ hết hạn trong 30 phút nữa. Trân trọng</p><p>%s</p>',
  SEND_MAIL_SUCCESS: 'Send email successfully',
  SEND_MAIL_ERROR: 'There was an error sending mail to activated. Please check again',
  TOKEN_EXPIRED: 'Token is expired',
  VERIFIED_SUCCESS: 'User verified successfully',
  USER_NOT_FOUND: 'User not found',
  PRODUCT_NOT_FOUND: 'Product not found',
  IMAGE_NOT_FOUND: 'Image not found',
  NO_TOKEN: 'No token',
  USERNAME_REQUIRED: 'Username is required',
  PASSWORD_REQUIRED: 'Password is required',
  PASSWORD_STRONG:
    'Password must be strong. At least one uppercase, lowercase letter. At least one number and special characters',
  EMAIL_REQUIRED: 'Email is required',
  USER_UPDATE_ERROR: 'There was an error while updating the user',
  PASSWORD_LENGTH_MISMATCH: 'Password must be at least %s characters',
  PASSWORD_INCORRECT: 'Invalid old password',
  PASSWORD_CHANGE_SUCCESS: 'Password changed successfully',
  SIGNIN_INVALID_EMAIL_PASSWORD: 'Invalid email or password',
  NO_FILE_UPLOAD: 'No file upload',
  DELETED_IMAGE_SUCCESS: 'Deleted image successfully',
  NEW_ORDER_MAILING_SUBJECT: 'No reply - Đơn hàng mới được đặt từ Amazon',
  NEW_ORDER_MAILING_HTML:
    '<p>Xin chào %s. Hệ thống đã nhận được đơn hàng mà bạn đã đặt trên website của chúng tôi như sau:<br /></p><p><strong>Tài khoản đặt: %s</strong></p><p><strong>Số sản phẩm: %s</strong></p><p><strong>Số tiền: %s</strong></p><p><strong>Hình thức thanh toán: %s</strong></p><br /><p>Mọi thắc mắc xin liên hệ số điện thoại: 0354321915</p>',
  CREATE_ORDER_SUCCESS: 'Create order successfully',
  CREATE_ORDER_FAIL: 'Create failure',
  ORDER_NOT_FOUND: 'Order not found',
  SEARCH_TEXT_REQUIRED: 'Search text required',
  FIELD_REQUIRED: '%s is required',
  REGISTERED_SUCCESS: 'Registered successfully',
  INVALID_USER: 'Invalid user',
  ORDER_UPDATE_SUCCESS: 'Updated order successfully',
  ORDER_ID_REQUIRED: 'Order id required',
  PRODUCT_ID_REQUIRED: 'Product id required',
  RATING_NUMBER_ERROR: 'Invalid rating number. It must be between 0 and 5',
  UPDATE_SUCCESS: 'Update successfully',
  UPDATE_ERROR: 'Update failure',
  BRAND_NOT_FOUND: 'Brand not found',
  PRODUCT_UPDATE_SUCCESS: 'Product update successfully',
}
